# Configuração para a predição de genes
[predictor_params]


# Configurações para o alinhador DIAMOND
[aligner_params]
  max_target_seqs = 8000
  query_cover = 75
  subject_cover = 75
  min_score = 30
  threads = 8

# Parâmetros para o filtro de RBH
[filter_params]
  meta = true
  threads = 8

# Parâmetros para o agrupador
[clusterer_params]
  num_trials = 3
